version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes: 
      - data-mysql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    ports: 
      - 3306:3306

  api:
    build: .
    environment: 
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_ADDR: db
      DB_DATABASE: $DB_DATABASE
    ports:
      - 3000:3000

volumes:
  data-mysql: